### ISSUE TITLE
Animate out query

### ISSUE THREAD

**Issue by graemegeorge** [rgabs/react-native-modal-overlay#8]
Great work here. I just have one query. 

As far as I can tell, the overlay animates **in** when the `visible` prop becomes `true`. But I cannot see a way to make it animate **out** when the `visible` prop becomes `false`. 

Is this possible in any way? (I have set `childrenWrapperStyle` to max width and height, so no overlay background to click)

Thanks for your time, hope you can help :)

**Comment by rgabs** [comment]
The whole modal content should fade out when it is closed. Have a look at https://github.com/rgabs/react-native-modal-overlay-example 
Let me know if it doesn't work

**Comment by niklassaers** [comment]
Thanks for a great library. :-)

I'm facing the same issue. When I tap outside the modal, it animates nicely out. But I have a dismiss button in my modal that sets isVisible = false, and that becomes instant invisible without animation.

I was looking for a way for the button to ask the overlay to dismiss so that it can use the same animate out as tapping outside the modal, but didn't find it. I looked at the example, but it doesn't contain a dismiss button in the modal.

Do you have any pointers for me?

**Comment by niklassaers** [comment]
So what I do currently is first grab a reference when I define the overlay:
`<Overlay ref={component => this._theOverlay = component}  .... />`
and then I call hide from the button I made to close the overlay:
`this._theOverlay._hideModal()`
Seems a bit brutal, and by the end I have to update Overlay's "visible" property so that is is false, giving a quick flash between the dark background and it being invisible. It works - kind of - but I'd love suggestions on how to improve it :-)

**Comment by rgabs** [comment]
Hi @niklassaers,
I have fixed the issue in the new release. 
Please have a look [here](https://github.com/rgabs/react-native-modal-overlay#complex-usage-with-render-props) to see how to use the new version of the component. It is backward compatible though :)

**Comment by niklassaers** [comment]
Wonderful, thank you :-)
